#Numpy

The numpy package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. In the numpy package the terminology used for vectors, matrices and higher-dimensional data sets is array.

## Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

## how to install and import?
To use numpy you need to import the module, using for example:

Firstly, You write **pip install numpy** in the command prompt (CMD) if you are on Windows.
And, most of the times py -m pip install numpy helps more on Windows.

On macOS/Unix, you can use python **-m pip install numpy** in terminal/console.

NumPy is usually imported under the np alias. you can choose any alias. Create an alias with the as keyword while importing like:

In [1]:
from numpy import *
import numpy as np

Now NumPy is imported and ready to use.

## creating Numpy Array
There are a number of ways to initialize new numpy arrays, for example from



*   a Python list or tuples
*   using functions that are dedicated to generating numpy arrays, such as arange, linspace, etc
*   reading data from files

### Using Python list or tuples
For example, to create new vector and matrix arrays from Python lists we can use the np.array function.

In [2]:
# a vector: the argument to the array function is a Python list
M= np.array([1, 2, 3, 4, 5])

print(M)
print(type(M))

#type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.

[1 2 3 4 5]
<class 'numpy.ndarray'>

In [3]:
# a matrix: the argument to the array function is a nested Python list
N = np.array([[1, 2], [3, 4]])

print(N)
print(type(N))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>

####Size and Shape:
The difference between the v and M arrays is only their shapes. We can get information about the shape of an array by using the ndarray.shape property. Equivalently, we could use the function np.shape and np.size

In [4]:
M.shape

(5,)

In [5]:
N.shape

(2, 2)

In [6]:
N.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [7]:
M.size

5

In [8]:
N.size

4

####dtype:
Using the dtype (data type) property of an ndarray, we can see what type the data of an array has:

In [9]:
M.dtype
N.dtype

dtype('int64')

In [10]:
N[0,0] = "hello"

ValueError: invalid literal for int() with base 10: 'hello'

If we want, we can explicitly define the type of the array data when we create it, using the dtype keyword argument:

In [11]:
P = np.array([[1, 2], [3, 4]], dtype=complex)

P

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Common data types that can be used with dtype are: int, float, complex, bool, object, etc.

We can also explicitly define the bit size of the data types, for example: int64, int16, float128, complex128.

###Using array-generating functions

For larger arrays it is impractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in numpy that generate arrays of different forms. Some of the more common are:

####Arange:

In [12]:
# create a range

x = arange(0, 10, 1) # arguments: start, stop, step

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x = arange(-1, 1, 0.1)

x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

####linspace and logspace

In [14]:
# using linspace, both end points ARE included
linspace(0, 10, 9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [15]:
logspace(0, 10, 10, base=e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

####random data

In [16]:
from numpy import random

In [17]:
# uniform random numbers in [0,1]
random.rand(5,5)

array([[0.06396048, 0.63603718, 0.4961951 , 0.66456802, 0.18883015],
       [0.26691421, 0.25253533, 0.20124545, 0.80749299, 0.12634816],
       [0.18593668, 0.37399185, 0.6257147 , 0.98065251, 0.36413623],
       [0.52139105, 0.08155198, 0.06559698, 0.46395224, 0.38249325],
       [0.65131486, 0.07213392, 0.99698994, 0.47362199, 0.43571666]])

In [18]:
# standard normal distributed random numbers
random.randn(5,5)

array([[ 0.78770065,  0.54122956, -1.12390434,  0.53364047,  1.91306458],
       [-0.88949355,  0.73864814, -0.2784606 ,  0.717052  ,  0.06104641],
       [ 0.52713578, -0.63825151,  0.74098281, -1.83426854, -0.66005027],
       [ 1.21281624,  0.45543001,  0.56757913, -1.49744739, -1.18565119],
       [-1.16144248,  2.25794494, -0.37783883, -1.0390652 ,  0.51763052]])

In [19]:
#random int numbers
np.random.randint(1,5,10)

array([3, 4, 2, 2, 2, 1, 3, 1, 4, 4])

####diagonal matrix

In [20]:
# a diagonal matrix
a=diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [21]:
a.diagonal()

array([1, 2, 3])

In [22]:
# diagonal with offset from the main diagonal
diag([1,2,3], k=2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

####zeros and ones

In [23]:
zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

####identity matrix

In [25]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

###reading data from files
A very common file format for data files is comma-separated values (CSV), or related formats such as TSV (tab-separated values). To read data from such files into Numpy arrays we can use the numpy.genfromtxt function. For example,

####CSV

#pandas

Pandas is a fast, powerful, flexible and easy-to-use open source data analysis and manipulation tool built on top of the Python programming language.

It is also one of the most popular libraries used by data experts from all around the world.

##What can you do with pandas?

Pandas is used for data wrangling, data analysis and data visualisation.

Some examples include creating and merging dataframes, dropping unwanted columns and rows, locating and filling null values, grouping data by category, creating basic plots like barplot, scatter plot, histogram etc.

##Why should you learn to use pandas?

As humans interact more and more with technology, vast amounts of data are being generated each day. Hence, the ability to analyse these data and draw insights from them is becoming an increasingly important skill to have in the modern workforce. Organisations are progressively turning to data to help them better understand their customers and products, analyse past trends and patterns, improve operational efficiency and so on.

Here are just some of the many reasons why you should learn pandas:

1. By learning pandas, you learn the fundamental ideas behind
working with data as well as some skill and knowledge to code in Python
2. It is straightforward to learn and you can immediately apply it to any dataset you want
3. It is commonly used in the data science and machine learning community

In [26]:
import pandas as pd

In [27]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], columns=["A", "B", "C"], index=["x","y","z",'zz'])

In [28]:
df.head()

     A   B   C
x    1   2   3
y    4   5   6
z    7   8   9
zz  10  11  12

In [29]:
df.tail(2)

     A   B   C
z    7   8   9
zz  10  11  12

In [30]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [31]:
df.index

Index(['x', 'y', 'z', 'zz'], dtype='object')

In [32]:
df.index.tolist()

['x', 'y', 'z', 'zz']

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, x to zz
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes

In [34]:
df.describe()

               A          B          C
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000

The describe() function with include='all' gives the summary statistics of all the columns.

In [35]:
df.describe(include='all')

               A          B          C
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000

##Computation of measures of central tendency

###Mean

In [36]:
mean = df['A'].mean()

print(mean)

5.5

###Median

In [37]:
median = df['B'].median()

print(median)

6.5

###Mode

In [38]:
mode = df['C'].mode()

print(mode)

0     3
1     6
2     9
3    12
Name: C, dtype: int64

In [39]:
df.nunique()

A    4
B    4
C    4
dtype: int64

In [40]:
df['A'].unique()

array([ 1,  4,  7, 10])

In [41]:
df.shape

(4, 3)

In [42]:
df.size

12

In [43]:
df

     A   B   C
x    1   2   3
y    4   5   6
z    7   8   9
zz  10  11  12

##Loading in Dataframes from Files

In [48]:
coffee = pd.read_csv('coffee.csv')
# olympics_data = pd.read_excel('olympics-data.xlsx', sheet_name="results")
bios = pd.read_csv('bios.csv')

##Accessing Data with Pandas

In [49]:
print(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [50]:
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [51]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [52]:
coffee.tail(10)

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [53]:
coffee.sample(5) # Pass in random_state to make deterministic

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
11   Saturday       Latte          35
3     Tuesday       Latte          20
9      Friday       Latte          35
12     Sunday    Espresso          45

In [54]:
# loc
# coffee.loc[Rows, Columns]

coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [55]:
coffee.loc[[0,1,5]]

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
5  Wednesday       Latte          25

In [56]:
coffee.loc[5:9, ["Day", "Units Sold"]]

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30
8     Friday          45
9     Friday          35

##iloc

In [57]:
coffee.iloc[:, [0,2]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [58]:
coffee.index = coffee["Day"]

In [59]:
coffee.index

Index(['Monday', 'Monday', 'Tuesday', 'Tuesday', 'Wednesday', 'Wednesday',
       'Thursday', 'Thursday', 'Friday', 'Friday', 'Saturday', 'Saturday',
       'Sunday', 'Sunday'],
      dtype='object', name='Day')

In [60]:
coffee.loc["Monday":"Wednesday"]

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25

##Setting Values

In [64]:

# coffee.loc[1:3, "Units Sold"] = 10
display(coffee)

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25
Thursday    Thursday    Espresso          40
Thursday    Thursday       Latte          30
Friday        Friday    Espresso          45
Friday        Friday       Latte          35
Saturday    Saturday    Espresso          45
Saturday    Saturday       Latte          35
Sunday        Sunday    Espresso          45
Sunday        Sunday       Latte          35

The error occurs because you are attempting to use positional slicing (1:3) with .loc, which is meant for label-based indexing. Positional slicing like 1:3 should be used with .iloc.

1. Use .iloc for positional indexing: If you want to assign values to rows 1 to 3 based on their positions:

In [65]:
coffee.iloc[1:3, coffee.columns.get_loc("Units Sold")] = 10

Explanation:

iloc[1:4] selects rows based on their positions (Python slicing is exclusive of the end index, so 1:4 covers rows 1, 2, and 3).
columns.get_loc("Units Sold") retrieves the column position for "Units Sold".

2. Reset or modify the index to handle positional slicing with .loc: If the index is not label-based but you want it to act like one, you can reset the index:

In [66]:
coffee = coffee.reset_index(drop=True)  # Reset index to 0, 1, 2, ...
coffee.loc[1:3, "Units Sold"] = 10     # Now label-based slicing aligns with positional slicing

##Optimized way to get single values (.at & .iat)

In [ ]:
coffee.at[0,"Units Sold"]

In [ ]:
coffee.iat[3,1]

##Getting Columns

In [ ]:
coffee.Day

In [ ]:
coffee["Day"]

##Sort Values

In [ ]:
coffee.sort_values(["Units Sold"], ascending=False)

In [ ]:
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=[0,1])

##Filtering Data

In [ ]:
bios.head()

In [ ]:
bios.loc[bios["height_cm"] > 215]

In [ ]:
bios.loc[bios["height_cm"] > 215, ["name", "height_cm"]]

###Short-hand syntax (without .loc)

In [ ]:
bios[bios['height_cm'] > 215][["name","height_cm"]]

###Multiple filter conditions

In [ ]:
bios[(bios['height_cm'] > 215) & (bios['born_country']=='USA')]

###Filter by string conditions

In [ ]:
bios[bios['name'].str.contains("keith", case=False)]

In [ ]:
# Regex syntax
bios[bios['name'].str.contains('keith|patrick', case=False)]

##Adding / Removing Columns

In [ ]:
coffee.head()

In [ ]:
coffee['price'] = 4.99

###where()

In [ ]:
coffee['new_price'] = np.where(coffee['Coffee Type']=='Espresso', 3.99, 5.99)

In [ ]:
coffee

In [ ]:
coffee.drop(columns=['price'], inplace=True)

# the below would also have worked
# coffee = coffee.drop(columns=['price'])

In [ ]:
coffee = coffee[['Day', 'Coffee Type', 'Units Sold', 'new_price']]

In [ ]:
coffee['revenue'] = coffee['Units Sold'] * coffee['new_price']

In [ ]:
coffee

In [ ]:
coffee.rename(columns={'new_price': 'price'}, inplace=True)

In [ ]:
bios_new = bios.copy()

In [ ]:
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]

In [ ]:
bios_new.query('first_name == "Keith"')

In [ ]:
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])

In [ ]:
bios_new['born_year'] = bios_new['born_datetime'].dt.year

In [ ]:
bios_new[['name','born_year']]

##apply()
a new column height_category in the DataFrame bios by applying a conditional logic to classify each individual's height (in centimeters) into categories (Short, Average, or Tall).

In [ ]:

bios['height_category'] = bios['height_cm'].apply(lambda x: 'Short' if x < 165 else ('Average' if x < 185 else 'Tall'))

In [ ]:
def categorize_athlete(row):
    if row['height_cm'] < 175 and row['weight_kg'] < 70:
        return 'Lightweight'
    elif row['height_cm'] < 185 or row['weight_kg'] <= 80:
        return 'Middleweight'

    else:
        return 'Heavyweight'

bios['Category'] = bios.apply(categorize_athlete, axis=1)

In [ ]:
bios.head()

##Merging & Concatenating Data

In [ ]:
nocs = pd.read_csv('noc_regions.csv')

In [ ]:
bios_new = pd.merge(bios, nocs, left_on='born_country', right_on='NOC', how='left')

In [ ]:
bios_new.rename(columns={'region': 'born_country_full'}, inplace=True)

In [ ]:
usa = bios[bios['born_country']=='USA'].copy()
gbr = bios[bios['born_country']=='GBR'].copy()

In [ ]:
new_df = pd.concat([usa,gbr])

In [ ]:
new_df.tail()

In [ ]:
results = pd.read_parquet('results.parquet')
combined_df = pd.merge(results, bios, on='athlete_id', how='left')

In [ ]:
bios.tail()

In [ ]:
results.tail()

In [ ]:
combined_df.tail()

##Handling Null Values

In [ ]:
coffee.loc[[2,3], 'Units Sold'] = np.nan

In [ ]:
# Make sure to set this to your Units Sold column if you want these changes to stick
coffee['Units Sold'].fillna(coffee['Units Sold'].mean())

In [ ]:
# coffee['Units Sold'] = coffee['Units Sold'].interpolate()
coffee['Units Sold'].interpolate()

In [ ]:
display(coffee)

In [ ]:
coffee.dropna(subset=['Units Sold']) # Use inplace=True if you want to update the coffee df

In [ ]:
coffee[coffee['Units Sold'].notna()]

In [ ]:
coffee

##Iterate over dataframe with for loop

In [ ]:
for index, row in coffee.iterrows():
    print(index)
    print(row)
    print("Coffee Type of Row:", row["Coffee Type"])

##Aggregating Data

In [ ]:
bios.head()

In [ ]:
bios['born_city'].value_counts()

In [ ]:
bios[bios['born_country']=='USA']['born_region'].value_counts().head(10)

In [ ]:
bios[bios['born_country']=='USA']['born_region'].value_counts().tail(25)

###max, min

###Groupby function in Pandas

In [ ]:
coffee.groupby(['Coffee Type'])['Units Sold'].sum()

In [ ]:
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

In [ ]:
coffee.groupby(['Coffee Type', 'Day']).agg({'Units Sold': 'sum', 'price': 'mean'})

###Pivot Tables

In [ ]:
pivot = coffee.pivot(columns='Coffee Type', index='Day', values='revenue')

In [ ]:
pivot.sum()

In [ ]:
pivot.sum(axis=1)

###Using datetime with Groupby

In [ ]:
bios['born_date'] = pd.to_datetime(bios['born_date'])
bios['month_born'] = bios['born_date'].dt.month
bios['year_born'] = bios['born_date'].dt.year
bios.groupby([bios['year_born'],bios['month_born']])['name'].count().reset_index().sort_values('name', ascending=False)

#Matplotlib

##Load Necessary Libraries

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

##Basic Graph

In [ ]:
x = [0,1,2,3,4]
y = [0,2,4,6,8]

# Resize your Graph (dpi specifies pixels per inch. When saving probably should use 300 if possible)
plt.figure(figsize=(5,5), dpi=100)

# Line 1

# Keyword Argument Notation
#plt.plot(x,y, label='2x', color='red', linewidth=2, marker='.', linestyle='--', markersize=10, markeredgecolor='blue')

# Shorthand notation
# fmt = '[color][marker][line]'
plt.plot(x,y, 'b--', label='2x')

## Line 2

# select interval we want to plot points at
x2 = np.arange(0,4.5,0.5)

# Plot part of the graph as line
plt.plot(x2[:6], x2[:6]**2, 'r', label='X^2')

# Plot remainder of graph as a dot
plt.plot(x2[5:], x2[5:]**2, 'r--')

# Add a title (specify font parameters with fontdict)
plt.title('Our First Graph!')

# X and Y labels
plt.xlabel('X Axis')
plt.ylabel('Y Axis')

# X, Y axis Tickmarks (scale of your graph)
plt.xticks([0,1,2,3,4,])
#plt.yticks([0,2,4,6,8,10])

# Add a legend
plt.legend()

# Save figure (dpi 300 is good when saving so graph has high resolution)
plt.savefig('mygraph.png', dpi=300)

# Show plot
plt.show()

##Bar Chart

In [ ]:
labels = ['A', 'B', 'C']
values = [1,4,2]

plt.figure(figsize=(5,3), dpi=100)

bars = plt.bar(labels, values)

patterns = ['/', 'O', '*']
for bar in bars:
    bar.set_hatch(patterns.pop(0))

plt.savefig('barchart.png', dpi=300)

plt.show()

##Real World Examples
Download data as per your interest!!! In this tutorial we use csv of gas_prices.csv & gas_data.csv

##load gas file

In [ ]:
gas = pd.read_csv('gas_prices.csv')
coffee = pd.read_csv('coffee.csv')

gas.head(5)

In [ ]:
gas = pd.read_csv('gas_prices.csv')

plt.figure(figsize=(8,5))

plt.title('Gas Prices over Time (in USD)', fontdict={'fontweight':'bold', 'fontsize': 18})

plt.plot(gas.Year, gas.USA, 'b.-', label='United States')
plt.plot(gas.Year, gas.Canada, 'r.-')
plt.plot(gas.Year, gas['South Korea'], 'g.-')
plt.plot(gas.Year, gas.Australia, 'y.-')

# Another Way to plot many values!
# countries_to_look_at = ['Australia', 'USA', 'Canada', 'South Korea']
# for country in gas:
#     if country in countries_to_look_at:
#         plt.plot(gas.Year, gas[country], marker='.')

plt.xticks(gas.Year[::3].tolist()+[2012])

plt.xlabel('Year')
plt.ylabel('US Dollars')

plt.legend()

plt.savefig('Gas_price_figure.png', dpi=300)

plt.show()

##Load gas Data

In [ ]:
gas = pd.read_csv('gas_data.csv')

gas.head(5)

##Histogram

In [ ]:

plt.figure(figsize=(8, 5))
plt.hist(gas['USA'], bins=10, color='blue', edgecolor='black', alpha=0.7)
plt.title('Distribution of Gas Prices in the USA')
plt.xlabel('Gas Prices (USD)')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

##Line chart

In [ ]:
data = gas['USA']

sns.distplot(data, bins=10, hist=True, kde=True, label = 'USA')

In [ ]:
data = gas['USA']

# Create the histogram with KDE
plt.figure(figsize=(8, 5))
sns.histplot(data, bins=10, kde=True, color='blue', label='USA', alpha=0.7)

# Add title and labels
plt.title('Distribution of Gas Prices in the USA')
plt.xlabel('Gas Prices (USD)')
plt.ylabel('Frequency')
plt.legend()
plt.show()

##pie chart

In [ ]:
display(coffee)

In [ ]:
e = coffee.loc[coffee['Coffee Type'] == 'Espresso'].count()[0]
l = coffee.loc[coffee['Coffee Type'] == 'Latte'].count()[0]

plt.figure(figsize=(8,5))

labels = ['Espresso', 'Latte']
colors = ['#ff9999', '#66b3ff']

plt.pie([e,l], labels = labels, colors=colors, autopct='%.2f %%')

plt.title('coffee Preference')

plt.show()

In [ ]:

coffee['Units Sold'] = [int(x.strip('lbs')) if isinstance(x, str) else x for x in coffee['Units Sold']]


light = coffee[coffee['Units Sold'] < 10].shape[0]
light_medium = coffee[(coffee['Units Sold'] >= 10) & (coffee['Units Sold'] < 15)].shape[0]
medium = coffee[(coffee['Units Sold'] >= 15) & (coffee['Units Sold'] < 30)].shape[0]
medium_heavy = coffee[(coffee['Units Sold'] >= 30) & (coffee['Units Sold'] < 45)].shape[0]
heavy = coffee[coffee['Units Sold'] >= 45].shape[0]


units_sold = [light, light_medium, medium, medium_heavy, heavy]
labels = ['under 10', '10-15', '15-30', '30-45', 'over 45']
explode = (0.4, 0.2, 0, 0, 0.4)


plt.figure(figsize=(8, 5), dpi=100)
plt.style.use('ggplot')
plt.title('cost of Coffee Sold ')

plt.pie(units_sold, labels=labels, explode=explode, pctdistance=0.8, autopct='%.2f %%')
plt.show()

##Box and Whiskers Chart

In [ ]:
# Select numerical columns for gas prices
countries = gas.columns[1:]  # Exclude the "Year" column

# Create a boxplot for gas prices across countries
plt.figure(figsize=(12, 6))
gas[countries].boxplot(patch_artist=True, boxprops=dict(facecolor='lightblue'))

# Add labels and title
plt.title('Boxplot of Gas Prices Across Countries (1990-2008)', fontsize=14)
plt.xlabel('Countries', fontsize=12)
plt.ylabel('Gas Prices (USD)', fontsize=12)

# Show the plot
plt.xticks(rotation=45)  # Rotate x-axis labels for better readability
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
car = pd.read_csv('CarPrice_project.csv')

In [ ]:
display(car)

In [ ]:
j=car['carbody']
print(j.head())  # View the first few rows
print(j.info())  # Check the structure of the DataFrame

##wordplot

In [ ]:
text = ' '.join(car['carbody'])

In [ ]:
import matplotlib.pyplot as plt

from wordcloud import WordCloud, STOPWORDS
#text = 'cat cat cat cat cat cat dog dog dog dog dog panda panda panda panda koala koala koala rabbit rabbit fox'

wordcloud = WordCloud().generate(text)
plt.imshow(wordcloud)
plt.title('Words by their frequency in the text')
plt.axis('off')
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Extract data
x = car['enginesize']
y = car['horsepower']
z = car['price']

# Normalize z to improve color variation
z_norm = (z - z.min()) / (z.max() - z.min())

# Create grid for contour
X, Y = np.meshgrid(np.linspace(x.min(), x.max(), 100), np.linspace(y.min(), y.max(), 100))
Z = np.interp(np.sqrt((X - x.mean())**2 + (Y - y.mean())**2), np.sort(z_norm), z_norm)

# Plot contour
plt.figure(figsize=(10, 6))
contour = plt.contourf(X, Y, Z, levels=50, cmap='viridis')  # Increased levels to 50
plt.colorbar(contour, label='Normalized Price')
plt.title('Contour Plot of Price Based on Engine Size and Horsepower')
plt.xlabel('Engine Size')
plt.ylabel('Horsepower')
plt.show()

##contour plot

In [ ]:
feature_x = np.arange(0, 50, 2)
feature_y = np.arange(0, 50, 3)

# Creating 2-D grid of features
[X, Y] = np.meshgrid(feature_x, feature_y)

fig, ax = plt.subplots(1, 1)

Z = np.cos(X / 2) + np.sin(Y / 4)

# plots contour lines
ax.contour(X, Y, Z)

ax.set_title('Contour Plot')
ax.set_xlabel('feature_x')
ax.set_ylabel('feature_y')

plt.show()

Plotting of contour using contourf() which plots filled contours.

In [ ]:
feature_x = np.linspace(-5.0, 3.0, 70)
feature_y = np.linspace(-5.0, 3.0, 70)

# Creating 2-D grid of features
[X, Y] = np.meshgrid(feature_x, feature_y)

fig, ax = plt.subplots(1, 1)

Z = X ** 2 + Y ** 2

# plots filled contour plot
ax.contourf(X, Y, Z)

ax.set_title('Filled Contour Plot')
ax.set_xlabel('feature_x')
ax.set_ylabel('feature_y')

plt.show()